# Generated by Django 2.2.5 on 2019-09-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0002_auto_20190903_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='idade',
            field=models.IntegerField(verbose_name='Idade'),
        ),
    ]
